import React from 'react';
import { View, Text, StyleSheet, Pressable, ScrollView } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useNavigation } from '@react-navigation/native';
import { Ionicons } from '@expo/vector-icons';
import { colors, fonts, spacing } from '../../theme';

const LAST_UPDATED = 'May 14, 2026';

export default function TermsOfServiceScreen() {
  const navigation = useNavigation();

  return (
    <SafeAreaView style={styles.container} edges={['top']}>
      <View style={styles.header}>
        <Pressable style={styles.backButton} onPress={() => navigation.goBack()} hitSlop={12}>
          <Ionicons name="chevron-back" size={28} color={colors.textPrimary} />
        </Pressable>
        <Text style={styles.headerTitle}>Terms of Service</Text>
        <View style={styles.headerSpacer} />
      </View>

      <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
        <Text style={styles.intro}>
          Welcome to MarchBuddy. These Terms of Service ("Terms") govern your use of the
          MarchBuddy mobile application and related services. By creating an account or using the
          app, you agree to these Terms. Please read them carefully.
        </Text>
        <Text style={styles.meta}>Last updated: {LAST_UPDATED}</Text>

        <Section title="1. Eligibility">
          <Paragraph>
            You must be at least 13 years old (or the minimum legal age in your country) to use
            MarchBuddy. By using the app you confirm that:
          </Paragraph>
          <BulletItem>You meet the minimum age requirement.</BulletItem>
          <BulletItem>The information you provide during sign-up is accurate.</BulletItem>
          <BulletItem>You have the legal authority to enter into this agreement.</BulletItem>
          <BulletItem>You are not barred from using the app under any applicable law.</BulletItem>
        </Section>

        <Section title="2. Your Account">
          <Paragraph>
            You are responsible for keeping your login credentials secure and for all activity
            that happens under your account. If you suspect unauthorized access, contact us
            immediately at <Bold>support@marchbuddy.com</Bold>. We are not liable for losses
            resulting from credentials you failed to protect.
          </Paragraph>
          <Paragraph>
            You may have only one personal account. Sharing your account or letting others use it
            is not permitted.
          </Paragraph>
        </Section>

        <Section title="3. Health & Fitness Disclaimer">
          <Paragraph>
            MarchBuddy is a <Bold>fitness and motivation tool — not medical advice</Bold>.
            Workouts, AI coaching, recommended sessions, nutrition logs, and feedback are intended
            for general fitness and educational purposes only.
          </Paragraph>
          <Paragraph>
            Before starting any exercise program or making changes to your nutrition or hydration:
          </Paragraph>
          <BulletItem>
            Consult a qualified medical professional, especially if you have any pre-existing
            health condition, injury, are pregnant, or have concerns about your fitness.
          </BulletItem>
          <BulletItem>
            Listen to your body. Stop any activity that causes pain, dizziness, shortness of
            breath, or feels unsafe.
          </BulletItem>
          <BulletItem>
            Do not ignore medical advice or delay seeking medical attention because of something
            you read or were told by the AI coach.
          </BulletItem>
          <Paragraph>
            You use the app entirely at your own risk. By tapping "Start Session" or otherwise
            following any advice or plan generated by MarchBuddy, you accept this risk.
          </Paragraph>
        </Section>

        <Section title="4. MarchBuddy Pro Subscription">
          <Paragraph>
            MarchBuddy offers a Pro subscription with monthly and annual billing options. Pro
            subscriptions are sold and processed by Google Play Billing (on Android) or the Apple
            App Store (on iOS).
          </Paragraph>

          <SubHeading>Auto-Renewal</SubHeading>
          <Paragraph>
            Subscriptions automatically renew at the end of each billing period (monthly or
            yearly) for the same duration, at the same price (subject to your platform's terms),
            unless you cancel at least 24 hours before the renewal date.
          </Paragraph>

          <SubHeading>Cancellation</SubHeading>
          <Paragraph>
            You can cancel anytime through your Google Play or Apple App Store subscription
            settings. Cancellation takes effect at the end of the current billing period — you
            keep Pro access until then but will not be charged again.
          </Paragraph>

          <SubHeading>Refunds</SubHeading>
          <Paragraph>
            Refund requests are handled by Google Play or the Apple App Store according to their
            policies. We do not process refunds directly. Mistaken purchases should be reported
            to the relevant store as soon as possible.
          </Paragraph>

          <SubHeading>Founding Member Pricing</SubHeading>
          <Paragraph>
            If you subscribe during our founding member period and keep your subscription active
            without lapse, you keep your original price even when prices increase for new
            customers. If your subscription lapses, future re-subscription will be at the then-
            current price.
          </Paragraph>

          <SubHeading>Free Trials</SubHeading>
          <Paragraph>
            If a free trial is offered, the trial converts to a paid subscription at the end of
            the trial period unless you cancel before then. Trials may not be available in all
            regions.
          </Paragraph>
        </Section>

        <Section title="5. Free Tier">
          <Paragraph>The free version of MarchBuddy gives you:</Paragraph>
          <BulletItem>Access to a limited set of training levels.</BulletItem>
          <BulletItem>A limited number of AI coach messages per day.</BulletItem>
          <BulletItem>Core session tracking, route maps, and basic progress views.</BulletItem>
          <Paragraph>
            Upgrade to Pro to unlock all levels, unlimited AI coaching, full community features,
            premium milestones, and early access to new features.
          </Paragraph>
        </Section>

        <Section title="6. Acceptable Use">
          <Paragraph>While using MarchBuddy, you agree NOT to:</Paragraph>
          <BulletItem>Use the app for any unlawful purpose.</BulletItem>
          <BulletItem>
            Attempt to reverse-engineer, decompile, scrape, or extract source code, training
            plans, coaching prompts, or other proprietary content from the app.
          </BulletItem>
          <BulletItem>
            Send harassing, abusive, discriminatory, harmful, sexually explicit, threatening,
            spammy, or illegal content to the AI coach or to other community members.
          </BulletItem>
          <BulletItem>
            Submit prompts intended to make the AI coach produce harmful, deceptive, or unsafe
            content.
          </BulletItem>
          <BulletItem>
            Share, sell, or transfer your Pro account to anyone, or use automation/bots to bypass
            free-tier limits or game challenges.
          </BulletItem>
          <BulletItem>
            Impersonate another person, misrepresent your identity, or post content you don't
            have the right to share.
          </BulletItem>
          <BulletItem>
            Upload images that contain other people's faces without their consent, or any content
            that is illegal, infringing, or sexually explicit.
          </BulletItem>
          <BulletItem>
            Interfere with the app's security, infrastructure, servers, or other users'
            experience.
          </BulletItem>
          <Paragraph>
            We may remove content, suspend access, or terminate accounts that violate these
            rules, with or without notice depending on the severity.
          </Paragraph>
        </Section>

        <Section title="7. Community Features">
          <Paragraph>
            MarchBuddy includes optional community features (challenges, teams, buddies, shared
            milestones). When you participate:
          </Paragraph>
          <BulletItem>
            Your chosen display name, progress, and content you share are visible to other members
            of the relevant group.
          </BulletItem>
          <BulletItem>
            You are responsible for the content you post. Be supportive and respectful of other
            users.
          </BulletItem>
          <BulletItem>
            We may remove community content that violates these Terms or that we consider unsafe,
            spammy, or off-topic.
          </BulletItem>
          <Paragraph>
            Sensitive onboarding answers (your trigger statement, anchor person, success vision,
            etc.) are <Bold>never shared</Bold> with other users.
          </Paragraph>
        </Section>

        <Section title="8. Your Content & Licenses">
          <Paragraph>
            When you complete sessions, log food (including food snap photos), write feedback,
            chat with the AI coach, or post in community spaces, that content stays{' '}
            <Bold>yours</Bold>.
          </Paragraph>
          <Paragraph>
            By using MarchBuddy, you grant us a limited, non-exclusive, royalty-free license to
            store, process, and display your content solely to provide the service to you and (in
            the case of community content) to share it with the audience you choose. This license
            ends when you delete the content or your account, except where retention is required
            by law.
          </Paragraph>
        </Section>

        <Section title="9. AI-Generated Output">
          <Paragraph>
            Coach feedback, training plans, motivational messages, and chat replies generated by
            the AI are produced automatically based on your data and your prompts.
          </Paragraph>
          <BulletItem>
            AI output may occasionally be inaccurate, incomplete, or generic. Use your judgment.
          </BulletItem>
          <BulletItem>
            AI suggestions are <Bold>not medical, legal, or professional advice</Bold>. See
            Section 3 for the health disclaimer.
          </BulletItem>
          <BulletItem>
            You may not represent AI-generated output as human-authored to deceive others.
          </BulletItem>
        </Section>

        <Section title="10. Intellectual Property">
          <Paragraph>
            MarchBuddy — including its name, logo, app interface, design, training programs, level
            structures, coaching prompts, milestone artwork, illustrations, source code, and
            documentation — is owned by us and protected by copyright, trademark, and other
            intellectual property laws.
          </Paragraph>
          <Paragraph>
            We grant you a personal, non-transferable, revocable license to use MarchBuddy for
            your personal, non-commercial fitness use only. You may not copy, redistribute, sell,
            sublicense, or create derivative works from any part of the app without our express
            written permission.
          </Paragraph>
        </Section>

        <Section title="11. Account Termination">
          <Paragraph>
            You can delete your account anytime from Settings → Delete Account. Deletion is
            permanent.
          </Paragraph>
          <Paragraph>We reserve the right to suspend or terminate accounts that:</Paragraph>
          <BulletItem>Violate these Terms.</BulletItem>
          <BulletItem>Engage in fraudulent activity, chargebacks, or refund abuse.</BulletItem>
          <BulletItem>Harm other users or compromise the service's safety.</BulletItem>
          <Paragraph>
            On termination by either side, your Pro subscription does not entitle you to a refund
            for the unused portion (unless required by law or your platform's policies).
          </Paragraph>
        </Section>

        <Section title="12. Disclaimers">
          <Paragraph>
            MarchBuddy is provided <Bold>"as is" and "as available"</Bold>, without warranties of
            any kind, express or implied — including warranties of merchantability, fitness for a
            particular purpose, non-infringement, or accuracy of AI-generated content.
          </Paragraph>
          <Paragraph>We do not guarantee that:</Paragraph>
          <BulletItem>The app will be uninterrupted, error-free, or always available.</BulletItem>
          <BulletItem>You will achieve specific fitness, weight, or health outcomes.</BulletItem>
          <BulletItem>The AI coach will always produce correct or appropriate suggestions.</BulletItem>
          <BulletItem>Route maps, distances, or other metrics will be perfectly accurate.</BulletItem>
        </Section>

        <Section title="13. Limitation of Liability">
          <Paragraph>
            To the maximum extent permitted by law, MarchBuddy and its team are <Bold>not liable
            </Bold> for any indirect, incidental, special, consequential, exemplary, or punitive
            damages arising from your use of the app, including:
          </Paragraph>
          <BulletItem>Personal injury, soreness, or harm during workouts.</BulletItem>
          <BulletItem>Loss of data, profits, or goodwill.</BulletItem>
          <BulletItem>Inaccurate AI advice or route data.</BulletItem>
          <BulletItem>Third-party service outages.</BulletItem>
          <Paragraph>
            Our total cumulative liability for any claims related to the app is limited to the
            greater of (a) the amount you paid us for Pro in the 12 months before the claim, or
            (b) USD 50.
          </Paragraph>
        </Section>

        <Section title="14. Indemnification">
          <Paragraph>
            You agree to indemnify and hold MarchBuddy harmless from claims, damages, and expenses
            (including reasonable legal fees) arising from:
          </Paragraph>
          <BulletItem>Your use of the app in violation of these Terms.</BulletItem>
          <BulletItem>Content you submit that infringes someone's rights.</BulletItem>
          <BulletItem>Your failure to follow medical advice or the health disclaimer.</BulletItem>
        </Section>

        <Section title="15. Changes to These Terms">
          <Paragraph>
            We may update these Terms from time to time as the app evolves or as the law changes.
            When we do, we'll update the "Last updated" date above. Material changes will be
            communicated through an in-app notice. Your continued use of the app after changes
            take effect means you accept the updated Terms.
          </Paragraph>
        </Section>

        <Section title="16. Governing Law & Dispute Resolution">
          <Paragraph>
            These Terms are governed by the laws of the jurisdiction in which MarchBuddy operates.
            Any disputes that cannot be resolved informally will be brought to the courts of that
            jurisdiction, unless local law requires otherwise.
          </Paragraph>
          <Paragraph>
            Before filing any formal complaint, please reach out to us at{' '}
            <Bold>support@marchbuddy.com</Bold> — most issues can be resolved quickly and without
            escalation.
          </Paragraph>
        </Section>

        <Section title="17. Severability">
          <Paragraph>
            If any part of these Terms is found to be unenforceable, the remaining parts will
            continue in full effect.
          </Paragraph>
        </Section>

        <Section title="18. Entire Agreement">
          <Paragraph>
            These Terms — together with our Privacy Policy and any platform-specific subscription
            terms (Google Play / App Store) — make up the entire agreement between you and
            MarchBuddy.
          </Paragraph>
        </Section>

        <Section title="19. Contact Us">
          <Paragraph>
            Questions about these Terms? Email us at <Bold>support@marchbuddy.com</Bold>. We're
            happy to help.
          </Paragraph>
        </Section>

        <View style={styles.bottomSpacer} />
      </ScrollView>
    </SafeAreaView>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <View style={styles.section}>
      <Text style={styles.sectionTitle}>{title}</Text>
      {children}
    </View>
  );
}

function SubHeading({ children }: { children: React.ReactNode }) {
  return <Text style={styles.subHeading}>{children}</Text>;
}

function Paragraph({ children }: { children: React.ReactNode }) {
  return <Text style={styles.paragraph}>{children}</Text>;
}

function Bold({ children }: { children: React.ReactNode }) {
  return <Text style={styles.bold}>{children}</Text>;
}

function BulletItem({ children }: { children: React.ReactNode }) {
  return (
    <View style={styles.bulletRow}>
      <Text style={styles.bulletDot}>•</Text>
      <Text style={styles.bulletText}>{children}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.divider,
  },
  backButton: {
    padding: 4,
  },
  headerTitle: {
    fontFamily: fonts.bold,
    fontSize: 18,
    color: colors.textPrimary,
  },
  headerSpacer: {
    width: 36,
  },
  scroll: {
    paddingHorizontal: spacing.screenPadding,
    paddingTop: 20,
  },
  intro: {
    fontFamily: fonts.regular,
    fontSize: 15,
    lineHeight: 22,
    color: colors.textSecondary,
    letterSpacing: 0.2,
  },
  meta: {
    fontFamily: fonts.medium,
    fontSize: 12,
    color: colors.textTertiary,
    marginTop: 10,
    letterSpacing: 0.3,
  },
  section: {
    marginTop: 28,
  },
  sectionTitle: {
    fontFamily: fonts.bold,
    fontSize: 17,
    color: colors.textPrimary,
    marginBottom: 10,
    letterSpacing: 0.2,
  },
  subHeading: {
    fontFamily: fonts.semiBold,
    fontSize: 14,
    color: colors.primary,
    marginTop: 12,
    marginBottom: 6,
    letterSpacing: 0.3,
  },
  paragraph: {
    fontFamily: fonts.regular,
    fontSize: 14,
    lineHeight: 21,
    color: colors.textSecondary,
    marginBottom: 10,
    letterSpacing: 0.15,
  },
  bold: {
    fontFamily: fonts.semiBold,
    color: colors.textPrimary,
  },
  bulletRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 8,
    paddingRight: 4,
  },
  bulletDot: {
    fontFamily: fonts.bold,
    fontSize: 14,
    color: colors.primary,
    marginRight: 10,
    lineHeight: 21,
  },
  bulletText: {
    fontFamily: fonts.regular,
    fontSize: 14,
    lineHeight: 21,
    color: colors.textSecondary,
    flex: 1,
    letterSpacing: 0.15,
  },
  bottomSpacer: {
    height: 40,
  },
});
